config/routes.rb
Netlab::Application.routes.draw do

  resources :workspace_tasks do
    member do
      put 'do_auto_task'
    end
  end

  resources :workspace_invitations
  
  resources :chat_invitations

  resources :workspaces do
    member do
      get 'manage'
      get 'conf'
      get 'download_captures'
    end
  end

  resources :workspaces

  resources :scenes do
    member do
      get 'delete'
      get 'back_edit_ajax'
      get 'show_edit_ajax'
    end

    collection do
      get 'back_new_ajax'
    end
  end

  resources :scenes
  resources :profiles do
    collection do
      get 'info'
    end
  end
  
  get '/help', to: 'help#index', as: 'help'

  mount Cloudstrg::Engine, :at => 'cloudstrg'
  mount Gdrivestrg::Engine, :at => 'gdrive'

  get "home/index"
  get "home/close"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins

  root :to => 'home#index'

end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  
  before_filter :check_notifications

  def index
  end

end

app/views/help/index.html.erb
<div class="container-fluid">

  <ul id="breadcrumb" class="breadcrumb wizard">
    <li><a href="/"><i class="icon-home"></i></a></li>
    <li class="active">Man</li>
  </ul>

  <div id="man" class="row-fluid container-widget">
    <div class="span3 bs-docs-sidebar">
      <ul class="nav bs-docs-sidenav affix">
        <li><a href="#"><i class="icon-chevron-right"></i> What is NetLAB?</a></li>
        <li><a href="#scenes"><i class="icon-chevron-right"></i> Scenes</a></li>
        <li><a href="#workspaces"><i class="icon-chevron-right"></i> Workspaces</a></li>
        <li><a href="#requirements"><i class="icon-chevron-right"></i> Requirements</a></li>
        <li><a href="#browser-support"><i class="icon-chevron-right"></i> Browser Support</a></li>
      </ul>
    </div>
      
    <div class="span9" data-spy="scroll" data-offset-top="0">
    
      <!-- What is NetLAB?
      ================================================== -->
      <section id="scenes">
        <div class="page-header">
          <h1>What is NetLAB?</h1>
        </div>
        
        NetLAB is an HTML5 Web application that allows several users
        to remotely operate a shared emulation of a TCP/IP
        network. NetLAB uses Netkit processes running on servers to
        emulate switches, routers, hosts and Ethernet.
        
        From the Web browser, NetLAB users can edit network diagrams,
        start/stop the nodes (hosts, routers and switches). All users
        working on the same emulated network share the console of each
        emulated node of the network. This way a user can see what
        another one is typing, what is useful for the purpose of
        learning. Users can also chat in realtime or talk among them
        using the collaboration tools offered by NetLAB.

	
        <br><br> A <a href="#scenes">scene</a> in NetLAB is used to
        edit a new network diagram. A user then can create
        a <a href="#workspaces">workspace</a> for launching and
        operating the emulated nodes described in the scene, being
        able to invite other users to share the emulated network.
      </section>
  
      <!-- Scenes
      ================================================== -->
      <section id="scenes">
        <div class="page-header">
          <h1>Scenes</h1>
        </div>
          
        <h3>How to create a scene</h3>
        <ul>
          <li>First, you have to go to page <%= link_to 'scenes', scenes_path %>.</li>
          <li>Click on <%= link_to '<i class="icon-plus icon-white"></i> New Scene'.html_safe, new_scene_path, 
            :class => 'btn btn-primary' %>
          <li>To add a node, simply click on it and drag it to the design area. You can add:</li>
            <p class="bs-docs-example"><img src="<%= asset_path('editor/image.png') %>" class="img-rounded" width="48" height="48">
            <img src="<%= asset_path('editor/router.png') %>" class="img-rounded" width="48" height="48">
            <img src="<%= asset_path('editor/switch.png') %>" class="img-rounded" width="48" height="48">
            <img src="<%= asset_path('editor/hub.png') %>" class="img-rounded" width="48" height="48"></p>
          <li>To join two nodes, click on <img src="<%= asset_path('editor/connect.png') %>" class="img-rounded" width="48" height="48">
          and then click on each node you want to join.</li>
          <li>To delete a link, click on <img src="<%= asset_path('editor/scissors.png') %>" class="img-rounded" width="48" height="48">
          and then click on the link you want to delete.</li>
          <li>Click on <button class="btn btn-primary" type="button">Save</button> to save the network design, 
          and write the name of the scene in a pop up window.</li>
          <li>If you want to reset the network, click on <button class="btn" type="button">Clear</button></li>
        </ul>

        <h3>How to edit a scene</h3>
        <p class="prettyprint-info">
          <strong>Info: </strong>One a scene has been associated with a Workspace you can no edit it.
        </p>
        <li>
          To edit a scene, you can click on the button
          <button class="btn btn-mini btn-info" type="button"><i class="icon-edit icon-white"></i></button>
          that appears on the right side of each scene in your list, or click on the same button that appears on the top right
          of each widget if you're watching a scene information.
        </li>
        <li>After modifying a scene, click on <button class="btn
        btn-primary" type="button">Save</button> to save changes.</li>

        <h3>How to remove a scene</h3>
        <p class="prettyprint-danger">
          <strong>Info: </strong>You can only remove a scene if this is not yet associated with a workspace.
        </p>
        <li>
          To remove a scene, click on the button
          <button class="btn btn-mini btn-danger" type="button"><i class="icon-trash icon-white"></i></button>
          that appears on the right side of each scene in your list.
        </li>
      </section>
  
      <!-- Workspaces
      ================================================== -->
      <section id="workspaces">
        <div class="page-header">
          <h1>Workspaces</h1>
        </div>

        <h3>How to create a workspace</h3>
        <ul>
          <li>First you have to go to page <%= link_to 'workspaces', workspaces_path %>.</li>
          <li>Click on <%= link_to '<i class="icon-plus icon-white"></i> New Workspace'.html_safe, new_workspace_path, 
            :class => 'btn btn-primary' %>
          <li>In the <code>New workspace</code> tab you must fill the field name, select the scene you want to use in  the workspace being created, 
          and load the configuration file. In the <code>Team</code> tab you can select which users will be able to work on this workspace.</li>
          <li>Click on <button class="btn btn-primary" type="button">Create Workspace</button> to save the workspace.
        </ul>
          
        <h3>How to edit a workspace</h3>
        <li>
          To edit a workspace, you can click on the button
          <button class="btn btn-mini btn-info" type="button"><i class="icon-edit icon-white"></i></button>
          that appears on the right side of each workspace in your list. Alternatively, you can  click on the same button that appears on the top right
          of each widget when you're watching information of a workspace, or operating it.
         </li>
         <li>After modifying the information of a Workspace click   <button class="btn btn-primary" type="button">Update Workspace</button>
         to save changes.</li>
           
        <h3>How to remove a workspace</h3>
        <p class="prettyprint-danger">
           <strong>Info: </strong>You can only remove a workspace if you are the owner.
        </p>
        <li>
          To remove a workspace, click on the button
          <button class="btn btn-mini btn-danger" type="button"><i class="icon-trash icon-white"></i></button>
          that appears on the right side of each workspace in your list.
        </li>
           
        <h3>How to manage a workspace</h3>
        <li>
          By clicking on the button
          <button class="btn btn-mini btn-warning"
          type="button"><i class="icon-wrench
          icon-white"></i></button> that appears on the right side of
          each workspace in your list you enter
          the <code>manage</code> mode of a workspace. In the manage
          mode users can run the emulated network. Alternatively, you
          can click on the same button that appears on the top right
          of each widget when you're watching information related to a
          workspace, or editing it.
        </li>
man        <li>
          To boot a virtual machine, click on
          <img src="<%= asset_path('editor/off.png') %>" class="img-rounded" width="60" height="60">. 
          When the virtual machine is powered on, you will see the icon
          <img src="<%= asset_path('editor/on.png') %>" class="img-rounded" width="60" height="60">
        </li>           
        <li>To start a terminal for that node, you have to click on that node.</li>
        <li>If you double-click on a machine that has started a terminal, the terminal is shown in the foreground.</li>
        <li>If you just want to close the terminal session, click on <img src="<%= asset_path('editor/shell.png') %>" 
          class="img-rounded" width="32" height="32"></li>
        <li>If you want to turn off the virtual machine, click on <img src="<%= asset_path('editor/on.png') %>" 
          class="img-rounded" width="60" height="60"></li>
          
        <h3>How to download captures of a workspace</h3>
        <p class="prettyprint-info">
          <strong>Info: </strong>To download captures of a workspace, you have to copy them to the directory 
          <em class="text-warning">/hostlab/captures</em>
        </p>
        <li>
          You can download network captures made on a workspace while
          you are <code>manage</code> mode by clicking on
          <button class="btn btn-success" type="button"><i class="icon-download icon-white"></i>Download captures</button>
        </li>
          
        <h3>How to work in groups in a workspace</h3>
        <li>First you will have to create a workspace and invite the users you want by selecting them in the team tab.
        When invited to a workspace by another user, you will receive notice of the invitation in the navigation bar.</li>
          <div class="bs-docs-example">
            <div class="btn">
              <%= '<i class="icon-bell"></i> Notifications'.html_safe %>
              <%= '<span class="badge badge-important">'.html_safe + "2" + '</span>'.html_safe %>
            </div>
          </div>
        <li>
          Click on the button and you will see a panel on the left side with the list of pending notifications.
          If you want to join the workspace click on
          <button class="btn btn-mini btn-success" type="button"><i class="icon-ok icon-white"></i></button>
          If you reject the invitation, click on
         <button class="btn btn-mini btn-danger" type="button"><i class="icon-remove icon-white"></i></button>
        </li>
        <li>
          To leave a workspace, click on the button
          <button class="btn btn-mini btn-danger" type="button"><i class="icon-remove icon-white"></i></button>
          that appears on the right side of each workspace in your list.
        </li>
        
        <h3>How to start a chat session</h3>
        <li>
          First, click on the button 
          <button class="btn"><i class="icon-comment"></i><span class="label">Ofline</span></button>
          to init a chat session. When the chat session is started the button toggles showing this icon: 
          <button class="btn"><i class="icon-comment"></i><span class="label label-success">Online</span></button>
        </li>
        <li>
          Click on the button right above and select "New invitation". Copy the link of the session in the text field and choose who you want to chat.
        </li>
        <li>
          Click on <button class="btn btn-primary"><i class="icon-share-alt icon-white"></i> Send Invitation</button> to send the invitation.
        </li>
      </section>
      
      <!-- Requirements
      ================================================== -->
      <section id="requirements">
        <div class="page-header">
          <h1>Requirements</h1>
        </div>
        
        You must have a Google account to access in NetLAB. You can create one <a href="https://accounts.google.com/signup?hl=en" 
        target="Google account">here</a>.
      </section>
      
      <!-- Browser Support
      ================================================== -->
      <section id="browser-support">
        <div class="page-header">
          <h1>Browser Support</h1>
        </div>
        
        NetLAB works best on modern browsers and some features only
        work on the most recent versions of some of these browsers.
        
        <h3>Supported Browsers</h3>
        We recommend the most recent release of <a href="https://www.google.com/intl/en/chrome/browser/">Chrome</a>.
        <br>If you want to
        use <a href="http://www.mozilla.org/en-US/firefox/new/">Firefox</a>
        it is possible that some characters like "-", "_" don't work
        on consoles of virtual machines.
        <br>It is possible to support Internet Explorer. However we do not test at all regularly on Internet Explorer.
      </section>
    
    </div>
  </div>

</div>