config/routes.rb
Netlab::Application.routes.draw do

  resources :workspace_tasks do
    member do
      put 'do_auto_task'
    end
  end

  resources :workspace_invitations
  
  resources :chat_invitations

  resources :workspaces do
    member do
      get 'manage'
      get 'conf'
      get 'download_captures'
    end
  end

  resources :workspaces

  resources :scenes do
    member do
      get 'delete'
      get 'back_edit_ajax'
      get 'show_edit_ajax'
    end

    collection do
      get 'back_new_ajax'
    end
  end

  resources :scenes
  resources :profiles do
    collection do
      get 'info'
    end
  end
  
  get '/help', to: 'help#index', as: 'help'

  mount Cloudstrg::Engine, :at => 'cloudstrg'
  mount Gdrivestrg::Engine, :at => 'gdrive'

  get "home/index"
  get "home/close"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins

  root :to => 'home#index'

end

app/models/workspace.rb
class Workspace < ActiveRecord::Base
  belongs_to :scene
  belongs_to :user
  has_and_belongs_to_many :editors, :class_name => User
  has_many :virtual_machines, dependent: :destroy
  has_many :collision_domains, dependent: :destroy
  has_many :workspace_invitations, dependent: :destroy
  has_many :workspace_tasks, dependent: :destroy
  has_one :scene_config, dependent: :destroy

  validates :user_id, :scene_id, :name, presence: true
  
  attr_accessor :share_ids, :unshare_ids, :session, :config_file

  after_save :invite_editors, :set_config_file
  before_destroy :unshare_editors

  private 
    def invite_editors
      if share_ids
        User.find(share_ids.gsub('_', '').split(',')).each do |user|
          #self.editors << user
          if not self.editors.include?(user)
            inv = user.workspace_invitations.find_by_workspace_id(self.id)
            if not inv
              inv = user.workspace_invitations.build(:workspace_id => self.id)
              inv.save
            end
          end
        end
      end
      if unshare_ids
        User.find(unshare_ids.gsub('_', '').split(',')).each do |user|
          #self.editors << user
          if self.editors.include? user
	    self.editors.delete(user)
            begin
              plugin = self.user.cloudstrgconfig.cloudstrgplugin
              session = {} if not session
              _params = {:user => self.user,
                       :plugin_id => plugin,
                       :redirect => "#{Netlab::Application.config.app_protocol}://#{Netlab::Application.config.app_host_and_port}/workspaces",
                       :file_id => self.scene.remote.file_remote_id,
                       :local_file_id => self.scene.remote.id,
                       :user_id => user.id,
                       :session => session}

              driver = CloudStrg.new_driver _params
              _session, url = driver.config _params
              session.merge!(_session)
              if not url
                driver.unshare_file _params
              end
            rescue Exception => e
              p 'Exception'
            end
          end
          inv = user.workspace_invitations.find_by_workspace_id(self.id)
          if inv
            inv.destroy
          end
        end
      end
    end

  private
  def set_config_file
    if config_file
      self.scene_config.destroy if self.scene_config
      ## SAVE FILE
      name = config_file.original_filename
      p "Saving file #{name}"
      directory = Rails.root.join('public', 'uploads')
      # create the file path
      path = File.join(directory,"#{rand(1000000000)}_#{name}")
      # write the file
      File.open(path, "wb") { |f| f.write(config_file.read)}

      ## UPLOAD FILE
      begin
        plugin = self.user.cloudstrgconfig.cloudstrgplugin
        p "Uploading file #{name} to #{plugin.plugin_name}"
        session = {} if not session
        _params = {:user => self.user,
                   :plugin_id => plugin,
                   :redirect => "#{Netlab::Application.config.app_protocol}://#{Netlab::Application.config.app_host_and_port}/workspaces",
                   :file => File.open(path, "rb"),
                   :filename => name,
                   :mimetype => 'application/x-gzip',
                   :session => session}

        driver = CloudStrg.new_driver _params
        _session, url = driver.config _params
        session.merge!(_session)
        if not url
          ro = driver.create_generic_file _params


          ## Creating scene config object in local database
          p "Creating scene config object for file #{name}"
          sc = self.build_scene_config(:user_id => self.user, :name => name)
          sc.remote = Cloudstrg::Remoteobject.find(ro.id)
          sc.save

          ## SET PERMISSIONS
          p "Making file #{name} public"
          _params = {:file_id => sc.remote.file_remote_id,
                     :local_file_id => ro.id,
                     :user_id => self.user.id}
          
          m_url = driver.share_public_file _params
          if m_url
            sc.url = m_url 
            sc.save
          end
        end
      rescue Exception => e
        p "Exception: #{e}"
      end


      ## REMOVE LOCAL FILE
      p "Remove local file #{name}"
      File.delete(path)
    end
  end

  private 
  def unshare_editors
    self.editors.each do |editor|
      begin
        plugin = self.user.cloudstrgconfig.cloudstrgplugin
        session = {} if not session
        _params = {:user => self.user,
               :plugin_id => plugin,
               :redirect => "#{Netlab::Application.config.app_protocol}://#{Netlab::Application.config.app_host_and_port}/workspaces",
               :file_id => self.scene.remote.file_remote_id,
               :local_file_id => self.scene.remote.id,
               :user_id => editor.id,
               :session => session}

        driver = CloudStrg.new_driver _params
        _session, url = driver.config _params
        session.merge!(_session)
        if not url
          driver.unshare_file _params
        end
      rescue Exception => e
        p 'Exception'
      end
    end
  end
end

app/controllers/workspaces_controller.rb
require 'cloudstrg/cloudstrg'
require 'net/http'
require 'bunny'

class WorkspacesController < ApplicationController
  before_filter :authenticate_user!, :except => [:conf]
  #before_filter :authenticate_admin!, :only => [:conf]
  before_filter :confWidget, :except => [:conf]
  before_filter :capture_cloudstrg_validation, :only => [:index]
  before_filter :check_notifications, :except => [:conf]

  def confWidget
    #TODO: Choose the widget that fits better in user's device screen
    @module = 'Desktop'
    @width = 600
    @height = 500
    @mode = "view"
  end

  # GET /workspaces
  # GET /workspaces.json
  def index
    @user = current_user
    @workspaces = @user.workspaces
    @workspaces += @user.editorworkspaces
    @workspace = @workspaces[0] # Default workspace

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workspaces }
    end
  end

  # GET /workspaces/1
  # GET /workspaces/1.json
  def show
    @user = current_user
    @workspace = Workspace.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workspace }
    end
  end

  # GET /workspaces/new
  # GET /workspaces/new.json
  def new
    @workspace = Workspace.new
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workspace }
    end
  end

  # GET /workspaces/1/manage
  def manage
    @workspace = Workspace.find(params[:id])
    @mode = "management"
    @handler = "WStreaming"

    respond_to do |format|
      format.html # manage.html.erb
      format.json { render json: @workspace }
    end
  end

  # GET /workspaces/1/edit
  def edit
    @workspace = Workspace.find(params[:id])
    
    respond_to do |format|
      @user = current_user
      if @user == @workspace.user
        format.html # manage.html.erb
        format.json { render json: @workspace }
      else
        flash[:notice] = "Forbidden action"
        format.html { redirect_to workspaces_path }
        format.json { render json: {:error => "Forbidden action"} }
      end
    end
    
  end

  # POST /workspaces
  # POST /workspaces.json
  def create
    @user = current_user
    @scene = Scene.find(params[:workspace][:scene_id])
    @workspace = @scene.workspaces.build(params[:workspace])
    @workspace.session = session
    @workspace.user = @user
    respond_to do |format|
      begin
        gen_schema get_scene(@scene, @user)
        err, host = NetlabAMQP.create_workspace(@workspace, @scene, @user)
        if (not err)
          @workspace.proxy = host
          @workspace.config_file = nil
          @workspace.save
          format.html { redirect_to @workspace, notice: 'Workspace was successfully created.' }
          format.json { render json: @workspace, status: :created, location: @workspace }
        else
          @workspace.destroy
          flash[:notice] = "Workspace could not be created"
          format.html { redirect_to workspaces_path }
          format.json { render json: {:error => "Can not create workspace"}}
        end
      rescue CloudStrg::ROValidationRequired => e
        #session[:stored_params] = params
        format.html {redirect_to e.message}
      rescue Exception => e
        puts e.message
        puts e.backtrace
        format.html { render action: "new" }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workspaces/1
  # PUT /workspaces/1.json
  def update
    @user = current_user
    @workspace = Workspace.find(params[:id])
    @workspace.session = session

    respond_to do |format|
      if current_user == @workspace.user
        if @workspace.update_attributes(params[:workspace])
          format.html { redirect_to @workspace, notice: 'Workspace was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @workspace.errors, status: :unprocessable_entity }
        end
      else
        flash[:notice] = "You are not allowed to do this action"
        format.html { render action: "edit" }
        format.json { render json: {:error => "not allowed"} }
      end
    end
  end

  # DELETE /workspaces/1
  # DELETE /workspaces/1.json
  def destroy
    @workspace = Workspace.find(params[:id])
    @user = current_user
    
    if @user == @workspace.user
      NetlabAMQP.destroy_workspace(@workspace)
      @workspace.destroy
    else
      @workspace.editors.delete(@user)
      @workspace.save
      scene = @workspace.scene
      user = scene.user
      plugin = scene.remote.cloudstrgplugin

      _session = {}
      _params = {:user => user,
               :plugin_id => plugin,
               :redirect => "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/workspaces",
               :file_id => scene.remote.file_remote_id,
               :local_file_id => scene.remote.id,
               :user_id => @user.id,
               :session => _session}

      driver = CloudStrg.new_driver _params
      _session, url = driver.config _params
      if not url
        driver.unshare_file _params
      end
    end

    respond_to do |format|
      format.html { redirect_to workspaces_url }
      format.json { head :no_content }
    end
  end

  # GET /workspaces/1/conf
  # GET /workspaces/1/conf.json
  def conf
    workspace = Workspace.find(params[:id])
    if workspace.scene_config
      if request.format == "html"
        # Generate filename
        uri = URI(workspace.scene_config.url)
        filename = workspace.scene_config.name
        directory = Rails.root.join('public', 'uploads')
        filepath = File.join(directory,"#{rand(1000000000)}")

        # Download file
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE

        req = Net::HTTP::Get.new(uri.request_uri)
        resp = http.request(req)

	if resp.code == "302"
          uri = URI(resp["location"])
          http = Net::HTTP.new(uri.host, uri.port)
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE

          req = Net::HTTP::Get.new(uri.request_uri)
          resp = http.request(req)
          
        end

        File.open(filepath, "wb") { |f| f.write(resp.body)}
      end
      respond_to do |format|
        format.html { send_file filepath, :filename => filename, :type => 'application/x-gzip' }
        format.json { render json: workspace.scene_config.to_json(:only => [:url]) }
      end
      if request.format == "html"
        File.delete(filepath)
      end
    else
      respond_to do |format|
        format.html { redirect_to workspace }
        format.json { head :no_content }
      end
    end
  end

  def compress_file(path)
    require 'zip/zip'
    require 'zip/zipfilesystem'

    path.sub!(%r[/$],'')
    archive = File.join(path,File.basename(path))+'.zip'
    FileUtils.rm archive, :force=>true

    Zip::ZipFile.open(archive, 'w') do |zipfile|
      Dir["#{path}/**/**"].reject{|f|f==archive}.each do |file|
        zipfile.add(file.sub(path+'/',''),file)
      end
    end
  end

  def download_captures
    @workspace = Workspace.find(params[:id])
    filepath = Netlab::Application.config.captures_path + "workspace#{@workspace.id}/netkit/captures/"
    filename = '/captures.zip'
    compress_file(filepath)
    begin
      send_file filepath + filename, :type => 'application/zip'
      File.delete(filepath + filename)
    rescue Exception => e
      respond_to do |format|
        format.html { redirect_to manage_workspace_path(@workspace), alert: 'Workspace has not captures.' }
      end
    end
  end

  private
  def create_iface(node, collision_domain)
    vm = VirtualMachine.find_by_name_and_workspace_id(node["name"], @workspace.id)
    if vm == nil
      @workspace.errors.add(:base, "Corrupted stage: Connection with an undefined node \"#{node["name"]}\"")
      raise
    end

    iface = Interface.new(
      name: node["iface"])
    iface.virtual_machine = vm
    iface.collision_domain = collision_domain
    iface
  end

  def create_collision_domain lan_id
    collision_domain = CollisionDomain.new
    collision_domain.workspace = @workspace
    collision_domain.name = "wk#{@workspace.id}cd#{lan_id[:id]}"
    lan_id[:id] = lan_id[:id] + 1
    collision_domain
  end

  def raise_error_if_exists(node, collision_domains)
    if node["type"] == "hub"
      vm = collision_domains[node["name"]]
    else
      vm = VirtualMachine.find_by_name_and_workspace_id(node["name"], @workspace.id)
    end

    return if (vm == nil)

    @workspace.errors.add(:base, "Corrupted stage: Node \"#{node["name"]}\" is not unique")
    raise
  end
  
  def get_scene(user, scene)
    _plugin = @scene.remote.cloudstrgplugin
    _params = {:user => @user, :plugin_id => _plugin, :redirect => "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/workspaces", :session => session}
    driver = CloudStrg.new_driver _params
    _session, url = driver.config _params
    session.merge!(_session)
    raise CloudStrg::ROValidationRequired, url if url
    
    _params = {:fileid => @scene.remote.file_remote_id}

    _, _, content = driver.get_file _params
    return JSON.parse content
  end

  def gen_schema definition
    collision_domains = {}
    lan_id = { id: 0}

    Workspace.transaction do
      @workspace.save!

      definition["nodes"].each do |node|
        raise_error_if_exists(node, collision_domains)

        case node["type"]
        when "hub"
          collision_domains[node["name"]] = create_collision_domain lan_id
          collision_domains[node["name"]].save!
        when "pc", "router", "switch"
          virtual_machine = VirtualMachine.new(
            node_type: node["type"],
            name: node["name"])
          virtual_machine.workspace = @workspace
          virtual_machine.save!

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/workspaces/_console_controller.js.erb
<%= javascript_tag do %>

ConsoleControler = (function () {
  var module = {};
  var console = null;

  module.manageConsole = function(conf) {
    var vm_name = conf["name"];
    var url = "http://" + conf["host"] + ":" + conf["port"];

    var html_code = '<iframe src="' + url + '" frameborder="1" width="830" height="480"></iframe>';

    $("#" + vm_name + " div.container").html(html_code);

    if (console) {
      $("#" + console).hide("blind", null, 1000, function() {
        $("#" + vm_name).show("blind", null, 1000, null);
      });
    } else
      $("#" + vm_name).show("fold", null, 1000, null);

    console = vm_name;
  };

  return module;

}());

<% end %>

app/views/workspaces/index.html.erb
<div class="container-fluid">

  <ul id="breadcrumb" class="breadcrumb wizard">
    <li><a href="/"><i class="icon-home"></i></a></li>
    <li class="active">Workspaces</li>
  </ul>

  <div class="row-fluid container-widget">

    <div id="netlab_params" class="span5">

      <%= link_to '<i class="icon-plus icon-white"></i> New Workspace'.html_safe, new_workspace_path, :class => 'btn btn-primary pull-right new' %>

      <div class="tabbable tabbable-bordered">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab"><h4>Listing workspaces</h4></a></li>
        </ul>
        <div class="tab-pane active" id="tab1">
          <table id="table_workspaces" class="table table-hover table-list">
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>User</th>
                <th>Scene</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% if @workspace.nil? %>
                <div class="alert alert-info">
                  You don't have any workspaces yet.
                </div>
              <% end %>
              <% @workspaces.each_with_index do |workspace, i| %>
                <tr>
                  <td>
                    <% if i == 0 %>
                      <%= radio_button_tag :id, workspace.scene_id, true, :class => workspace.name %>
                    <% else %>
                      <%= radio_button_tag :id, workspace.scene_id, false, :class => workspace.name %>
                    <% end %>
                  </td>
                  <td><%= workspace.name %></td>
                  <td><%= workspace.user.first_name %></td>
                  <td><%= workspace.scene.name %></td>
                  <td>
                    <%= link_to '<i class="icon-eye-open icon-white"></i>'.html_safe, workspace_path(workspace), :class => 'btn btn-success btn-mini',
			:title => 'Show', :rel => 'tooltip' %>
                    <%= link_to '<i class="icon-wrench icon-white"></i>'.html_safe, manage_workspace_path(workspace), :class => 'btn btn-warning btn-mini',
			:title => 'Manage', :rel => 'tooltip' %>
                    <% if @user.id == workspace.user.id %>
                      <%= link_to '<i class="icon-edit icon-white"></i>'.html_safe, edit_workspace_path(workspace), :class => 'btn btn-info btn-mini',
			  :title => 'Edit', :rel => 'tooltip' %>
                      <%= link_to '<i class="icon-trash icon-white"></i>'.html_safe, workspace, confirm: 'Are you sure?', method: :delete,
			  :class => 'btn btn-danger btn-mini', :title => 'Remove' %>
                    <% else %>
                      <%= link_to '<i class="icon-remove icon-white"></i>'.html_safe, workspace, confirm: 'Are you sure?', method: :delete,
			  :class => 'btn btn-mini btn-danger', :title => 'Leave'%>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>

    <% if not @workspace.nil? %>
      <div id="workspace_view" class="span6 offset1" >
        <div class="navbar">
          <div id="container_title" class="navbar-inner">
            <a id="workspace_title" href="#" class="brand">Loading...</a>
          </div>
        </div>

        <%= render 'scenes/netwidget' %>
      </div>
    <% end %>

  </div>

</div>

app/views/workspaces/manage.html.erb
<%= render partial: 'console_controller', formats: :js %>

<p id="notice"><%= notice %></p>

<%= hidden_field_tag 'workspace_scene_id', @workspace.scene.id %>

  <div class="container-fluid">

    <ul id="breadcrumb" class="breadcrumb wizard">
      <li><a href="/"><i class="icon-home"></i></a></li>
      <li><a href="/workspaces">Workspaces</a></li>
      <li><%= link_to @workspace.name, workspace_path(@workspace) %></li>
      <li class="active">Manage</li>
    </ul>

    <div class="row-fluid container-widget">

      <div id="netlab_params">
        <span id="scene_name" style="VISIBILITY:hidden"><%= @workspace.scene.name %></span>
      
        <center>
          <div class="control-btn">
            <%= link_to '<i class="icon-download icon-white"></i> Download captures'.html_safe, 
              download_captures_workspace_path(@workspace.id), :class => 'btn btn-success' %>
            
            <div class="btn-group">
              <button id="btn-chat" class="btn" onclick="switchChat(); TogetherJS(this); return false;">
                <i class="icon-comment"></i> <span id="btn-text-chat" class="label" value="0">Offline</span></button>
              <button class="btn dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href='#newInvitationModal' data-toggle="modal"><i class="icon-plus"></i> New invitation</a></li>
              </ul>
            </div>
            <a></a>
            <div class="btn-group">
              <button class="btn btn-info"><i class="icon-tasks icon-white"></i> Tasks</button>
              <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href='#newTaskModal' data-toggle="modal"><i class="icon-plus"></i> New task</a></li>
                <li><a href='#viewTaskModal' data-toggle="modal"><i class="icon-eye-open"></i> View all tasks</a></li>
              </ul>
            </div>
          </div>
        </center>

        <div id="newInvitationModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="newInvitationModalHeader">New chat invitation</h3>
          </div>
          <div class="modal-body">
            <%= render partial: 'chat_invitations/form', :locals => {:chat_invitation => ChatInvitation.new, :workspace => @workspace} %>
          </div>
        </div>

        <div id="newTaskModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="newInvitationModalHeader">New task</h3>
          </div>
          <div class="modal-body">
            <%= render partial: 'workspace_tasks/form', :locals => {:workspace_task => WorkspaceTask.new, :workspace => @workspace} %>
          </div>
        </div>

        <div id="viewTaskModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="viewTaskModalHeader">Tasks</h3>
          </div>
          <div class="modal-body">
             <%= render partial: 'workspace_tasks/workspace_tasks', :locals => {:workspace => @workspace} %>
          </div>
        </div>

        <div id="shellsModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="shellsModalHeader">Admin Panel</h3>
          </div>
          <div class="modal-body">
            <div id="shells" class="tabbable tabbable-bordered">
              <ul class="nav nav-tabs"></ul>
              <div id="tab-content" class="tab-content"></div>
            </div>
          </div>
        </div>
 
        <div id="loadingShellModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-body">
            <div id="loading-shell" class="progress progress-striped active">
              <div class="bar" style="width: 100%;"></div>
            </div>
          </div>
        </div>
      </div>

      <% if not @workspace.scene.nil? %>
        <div id="scene_manage">
          <div class="navbar">
            <div id="container_title" class="navbar-inner">
              <a id="workspace_title" href="#" class="brand">Loading...</a>
              <% if @workspace.id %>
                <span class="icon pull-right">
                  <%= link_to '<i class="icon-eye-open"></i>'.html_safe, @workspace, :title => 'Show', :rel => 'tooltip' %>
                </span>
                <span class="icon pull-right">
                  <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_workspace_path(@workspace), :title => 'Edit', :rel => 'tooltip' %>
                </span>
              <% end %>
            </div>
          </div>
          <%= render 'scenes/netwidget' %>
        </div>
      <% end %>

    </div>

  </div>

<div id="<%= @workspace.id %>" class="virtual_machines">
  <% VirtualMachine.find_all_by_workspace_id(@workspace.id).each do |vm| %>
    <div id="<%= vm.name %>" class="ui-widget-content ui-corner-all" style="display: none">
      <h3 class="ui-widget-header ui-corner-all"><%= vm.name %></h3>
      <div class="container"></div>
    </div>
  <% end %>
</div>

app/views/workspaces/new.html.erb
<%= render 'form' %>

app/views/workspaces/show.html.erb
<div class="container-fluid">

  <ul id="breadcrumb" class="breadcrumb wizard">
    <li><a href="/"><i class="icon-home"></i></a></li>
    <li><a href="/workspaces">Workspaces</a></li>
    <li class="active"><%= @workspace.name %></li>
  </ul>

  <div class="row-fluid container-widget">

    <div id="netlab_params" class="span5">

      <div class="tabbable tabbable-bordered">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab"><h4>Workspace Info</h4></a></li>
        </ul>
        <div id="tab-content" class="tab-content">
          <div class="tab-pane active" id="tab1">
            <table class="table table-list info">
              <tbody>
                <tr>
                  <td>
                    <p class="formSep"><small class="muted">Name: </small><%= @workspace.name %></p>
                    <p class="formSep"><small class="muted">Owner: </small>
                      <%= link_to "#{@workspace.user.first_name} #{@workspace.user.last_name}", profile_path(@workspace.user) %></p>
                    <p class="formSep"><small class="muted">Scene: </small><span id="scene_name"><%= @workspace.scene.name %></span></p>
                    <p class="formSep"><small class="muted">Config file: </small>
                      <% if @workspace.scene_config %>
                        <%= link_to "#{@workspace.scene_config.name}", 
                          "#{Netlab::Application.config.app_protocol}://#{Netlab::Application.config.app_host_and_port}//workspaces/#{@workspace.id}/conf"%></p>
                      <% end %>
                    <p class="formSep"><small class="muted">Collaborators: </small>
                    <% User.find(:all, :conditions => ["id != ?", @user.id]).each_with_index do |user, i| -%>
                      <% if @workspace.editors.include?(user) %>
                        <div class="span6">
                          <ul><%= link_to "#{user.first_name} #{user.last_name}", profile_path(user) %></ul>
                       </div>
                      <% end %>
                    <% end -%>
                    </p>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>

    <%= hidden_field_tag 'workspace_scene_id', @workspace.scene.id %>

    <div id="workspace_view" class="span6 offset1" >
      <div class="navbar">
        <div id="container_title" class="navbar-inner">
          <a id="workspace_title" href="#" class="brand">Loading...</a>
          <span class="icon pull-right">
            <%= link_to '<i class="icon-wrench"></i>'.html_safe, manage_workspace_path(@workspace), :title => 'Manage', :rel => 'tooltip' %>
          </span>
          <span class="icon pull-right">
            <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_workspace_path(@workspace), :title => 'Edit', :rel => 'tooltip' %>
          </span>
        </div>
      </div>

      <%= render 'scenes/netwidget' %>
    </div>

  </div>

</div>