config/routes.rb
Netlab::Application.routes.draw do

  resources :workspace_tasks do
    member do
      put 'do_auto_task'
    end
  end

  resources :workspace_invitations
  
  resources :chat_invitations

  resources :workspaces do
    member do
      get 'manage'
      get 'conf'
      get 'download_captures'
    end
  end

  resources :workspaces

  resources :scenes do
    member do
      get 'delete'
      get 'back_edit_ajax'
      get 'show_edit_ajax'
    end

    collection do
      get 'back_new_ajax'
    end
  end

  resources :scenes
  resources :profiles do
    collection do
      get 'info'
    end
  end
  
  get '/help', to: 'help#index', as: 'help'

  mount Cloudstrg::Engine, :at => 'cloudstrg'
  mount Gdrivestrg::Engine, :at => 'gdrive'

  get "home/index"
  get "home/close"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins

  root :to => 'home#index'

end

app/models/workspace_task.rb
class WorkspaceTask < ActiveRecord::Base
  attr_accessible :assigned_id, :author_id, :workspace_id, :auto_task, :description, :priority, :state, :subject

  belongs_to :author, :class_name => User, :foreign_key => :author_id
  belongs_to :assigned, :class_name => User, :foreign_key => :assigned_id

  belongs_to :workspace

  validates :priority, :inclusion => 0..4
  validates :state, :inclusion => 0..4

  def get_priority
    case self.priority
    when 0
      return "Very low"
    when 1
      return "Low"
    when 2
      return "Medium"
    when 3
      return "High"
    when 4
      return "Very high"
    end
  end

  def get_status
    case self.state
    when 0
      return "Open"
    when 1
      return "Resolved"
    when 2
      return "Feedback"
    when 3
      return "Fixed"
    when 4
      return "Closed"
    end
  end
end

app/controllers/workspace_tasks_controller.rb
class WorkspaceTasksController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_notifications

  # GET /workspace_tasks
  # GET /workspace_tasks.json
  def index
    @user = current_user

    respond_to do |format|
      format.html { render "index" }# index.html.erb
      format.json { render json: @user.assigned_workspace_tasks }
    end
  end

  # GET /workspace_tasks/1
  # GET /workspace_tasks/1.json
  def show
    @workspace_task = WorkspaceTask.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workspace_task }
    end
  end

  # GET /workspace_tasks/new
  # GET /workspace_tasks/new.json
  def new
    @workspace_task = WorkspaceTask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workspace_task }
    end
  end

  # GET /workspace_tasks/1/edit
  def edit
    @workspace_task = WorkspaceTask.find(params[:id])
  end

  # POST /workspace_tasks
  # POST /workspace_tasks.json
  def create
    @workspace_task = WorkspaceTask.new(params[:workspace_task])

    respond_to do |format|
      if @workspace_task.save
        format.html { redirect_to manage_workspace_path(@workspace_task.workspace), notice: 'Workspace task was successfully created.' }
        format.json { render json: @workspace_task, status: :created, location: @workspace_task }
      else
        format.html { render @workspace_task.workspace }
        format.json { render json: @workspace_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workspace_tasks/1
  # PUT /workspace_tasks/1.json
  def update
    @workspace_task = WorkspaceTask.find(params[:id])

    respond_to do |format|
      if @workspace_task.update_attributes(params[:workspace_task])
        format.html { redirect_to manage_workspace_path(@workspace_task.workspace), notice: 'Workspace task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @workspace_task.workspace, notice: 'Error saving task' }
        format.json { render json: @workspace_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workspace_tasks/1
  # DELETE /workspace_tasks/1.json
  def destroy
    @workspace_task = WorkspaceTask.find(params[:id])
    @workspace_task.destroy

    respond_to do |format|
      format.html { redirect_to workspace_tasks_url }
      format.json { head :no_content }
    end
  end

  # PUT /workspace_tasks/1/do_auto_task
  # PUT /workspace_tasks/1/do_auto_task.json
  def do_auto_task
    workspace_task = WorkspaceTask.find(params[:id])
    message = "ok"
    code = 200
    if workspace_task.auto_task == "SHARE SCENE"
      ws = workspace_task.workspace
      scene = ws.scene
      user = workspace_task.assigned
      plugin = scene.remote.cloudstrgplugin 
      _params = {:user => user,
                 :plugin_id => plugin,
                 :redirect => "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/scenes",
                 :file_id => scene.remote.file_remote_id,
                 :share_email => workspace_task.author.email,
                 :local_file_id => scene.remote.id,
                 :user_id => workspace_task.author.id,
                 :session => session}
      driver = CloudStrg.new_driver _params
      _session, url = driver.config _params
      session.merge!(_session)
      if not url
        driver.share_file _params
        workspace_task.state = 5
        workspace_task.save
      else
        message = "Scene not found"
        code = 500
      end
    else
      message = "Unknown task"
      code = 500
    end

    respond_to do |format|
      flash[:notice] = message
      format.html { redirect_to manage_workspace_path(ws) }
      format.json { render json: {:message => message}, status: code }
    end
  end
end

app/helpers/workspace_tasks_helper.rb
module WorkspaceTasksHelper
end

app/views/workspace_tasks/_form.html.erb
<%= form_for(workspace_task) do |f| %>
  <% if workspace_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workspace_task.errors.count, "error") %> prohibited this workspace_task from being saved:</h2>

      <ul>
      <% workspace_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if workspace_task.author.nil? %>
      <%= f.hidden_field :author_id, :value => "#{current_user.id}" %>
    <% else %>
      <%= f.hidden_field :author_id, :value => "#{workspace_task.author.id}" %>
    <% end %>

    <% if workspace_task.workspace.nil? %>
      <%= f.hidden_field :workspace_id, :value => "#{workspace.id}" %>
    <% else %>
      <%= f.hidden_field :workspace_id, :value => "#{workspace_task.workspace.id}" %>
    <% end %>

  <div class="field">
    <%= f.label :assigned_id, "Assigned to", :class => 'control-label' %>
    <% if workspace_task.assigned_id.nil? %>
      <%= f.select :assigned_id, options_from_collection_for_select([workspace.user] + workspace.editors, :id, :full_name) %>
    <% else %>
      <%= f.select :assigned_id, options_from_collection_for_select([workspace.user] + workspace.editors, :id, :full_name, workspace_task.assigned_id) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :state, "Status" %>
    <% if workspace_task.state.nil? %>
      <%= f.select :state, options_for_select(["Open", "Resolved", "Feedback", "Fixed", "Closed"].each_with_index.map { |v,i| [v, i] }) %>
    <% else %>
      <%= f.select :state, options_for_select(["Open", "Resolved", "Feedback", "Fixed", "Closed"].each_with_index.map { |v,i| [v, i] }, workspace_task.state) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :priority %>
    <% if workspace_task.priority.nil? %>
      <%= f.select :priority, options_for_select(["Very low", "Low", "Medium", "High", "Very High"].each_with_index.map { |v,i| [v, i] }, 2) %>
    <% else %>
      <%= f.select :priority, options_for_select(["Very low", "Low", "Medium", "High", "Very High"].each_with_index.map { |v,i| [v, i] }, workspace_task.priority) %>
    <% end %>

  </div>
  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="modal-footer">
    <center><%= f.submit 'Save', :class => 'btn btn-primary' %></center>
  </div>
<% end %>

app/views/workspace_tasks/_index.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a href="#" class="brand"><%= "#{@user.first_name}'s tasks" %></a>
    <span class="icon pull-right">
      <i class="icon-tasks"></i>
    </span>
  </div>
</div>

<table class="table table-hover table-list">
  <thead>
    <th></th>
    <th>Workspace Name</th>
    <th>State</th>
    <th>Priority</th>
    <th>Subject</th>
    <th>Date</th>
    <th>Actions</th>
  </thead>
  <% @user.assigned_workspace_tasks.where("state < 5").each do |wtask| %>
    <tbody>
      <tr>
        <td class="list-image"><i class="icon-chevron-right"></i></td>
        <td><span class="list-text"><%= "#{wtask.workspace.name}" %></span></td>
        <td><%= "#{wtask.get_status}" %></td>
        <td><%= "#{wtask.get_priority}" %></td>
        <td><%= "#{wtask.subject}" %></td>
        <td><%= ("#{wtask.created_at}").to_time.strftime("%Y/%m/%d") %></td>
        <td>
          <% if not wtask.auto_task.nil? %>
          <%= link_to '<i class="icon-ok icon-white"></i> Ok'.html_safe, do_auto_task_workspace_task_path(wtask), method: :put, :class => 'btn btn-mini btn-success' %>
          <% else %>
            <%= link_to '<i class="icon-eye-open icon-white"></i>'.html_safe, wtask, :class => 'btn btn-mini btn-success' %>
          <% end %>
          <%= link_to '<i class="icon-remove icon-white"></i>'.html_safe, wtask, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/workspace_tasks/_workspace_tasks.html.erb
<table id="table_tasks" class="table table-hover table-list">
  <thead>
    <tr>
      <th></th>
      <th>Assigned to</th>
      <th>Priority</th>
      <th>Subject</th>
      <th>Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% workspace.workspace_tasks.where("state < 4").each do |wtask| %>
      <tr>
        <td class="list-image"><i class="icon-tasks"></i></td>
        <td><%= "#{wtask.assigned.full_name}" %></td>
        <td><%= "#{wtask.get_priority}" %></td>
        <td><%= "#{wtask.subject}" %></td>
        <td><%= '<span class="minor">'.html_safe + ' On ' + ("#{wtask.created_at}").to_time.strftime("%B %d %Y %X") + '</span>'.html_safe %></td>
        <td>
          <% if not wtask.auto_task.nil? and current_user == wtask.assigned %>
            <%= link_to '<i class="icon-ok icon-white"></i> Ok'.html_safe, do_auto_task_workspace_task_path(wtask), method: :put, :class => 'btn btn-mini btn-success' %>
          <% else %>
            <%= link_to '<i class="icon-eye-open icon-white"></i>'.html_safe, wtask, :class => 'btn btn-mini btn-success' %>
          <% end %>
          <%= link_to '<i class="icon-remove icon-white"></i>'.html_safe, wtask, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workspace_tasks/edit.html.erb
<%= render :partial => 'form', :locals => {:workspace_task => @workspace_task, :workspace => @workspace_task.workspace} %>

app/views/workspace_tasks/new.html.erb
<h1>New workspace_task</h1>

<%= render 'form' %>

<%= link_to 'Back', workspace_tasks_path %>

app/views/workspace_tasks/show.html.erb
<div class="container-fluid">

  <ul id="breadcrumb" class="breadcrumb wizard">
    <li><a href="/"><i class="icon-home"></i></a></li>
    <li><a href="/workspaces">Workspaces</a></li>
    <li><%= link_to @workspace_task.workspace.name, workspace_path(@workspace_task.workspace) %></li>
    <li><%= link_to 'Manage', manage_workspace_path(@workspace_task.workspace) %></li>
    <li class="active">Task <%= @workspace_task.id %></li>
  </ul>

  <div class="row-fluid container-widget">

    <div id="netlab_params" class="span5">

      <% if current_user == @workspace_task.author or current_user == @workspace_task.assigned %>
        <a href='#newTaskModal' class='btn btn-info pull-right new' data-toggle="modal"><i class="icon-edit icon-white"></i></a>
      <% end %>

      <div id="newTaskModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="newTaskModalHeader">Edit Task</h3>
        </div>
        <div class="modal-body">
          <%= render partial: 'workspace_tasks/form', :locals => {:workspace_task => @workspace_task, :workspace => @workspace_task.workspace} %>
        </div>
      </div>

      <div class="tabbable tabbable-bordered">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab"><h4>Task Info</h4></a></li>
        </ul>
        <div id="tab-content" class="tab-content">
          <div class="tab-pane active" id="tab1">
            <table class="table table-list info">
              <tbody>
                <tr>
                  <td>
                    <p class="formSep"><small class="muted">Author: </small><%= link_to "#{@workspace_task.author.full_name}", profile_path(@workspace_task.author) %></p>
                    <p class="formSep"><small class="muted">Assigned to: </small><%= link_to "#{@workspace_task.assigned.full_name}", profile_path(@workspace_task.assigned) %></p>
                    <p class="formSep"><small class="muted">Status: </small><%= @workspace_task.get_status %></p>
                    <p class="formSep"><small class="muted">Priority: </small><%= @workspace_task.get_priority %></p>
                    <p class="formSep"><small class="muted">Subject: </small><%= @workspace_task.subject %></p>
                    <p class="formSep"><small class="muted">Description: </small><%= @workspace_task.description %></p>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>