config/routes.rb
Netlab::Application.routes.draw do

  resources :workspace_tasks do
    member do
      put 'do_auto_task'
    end
  end

  resources :workspace_invitations
  
  resources :chat_invitations

  resources :workspaces do
    member do
      get 'manage'
      get 'conf'
      get 'download_captures'
    end
  end

  resources :workspaces

  resources :scenes do
    member do
      get 'delete'
      get 'back_edit_ajax'
      get 'show_edit_ajax'
    end

    collection do
      get 'back_new_ajax'
    end
  end

  resources :scenes
  resources :profiles do
    collection do
      get 'info'
    end
  end
  
  get '/help', to: 'help#index', as: 'help'

  mount Cloudstrg::Engine, :at => 'cloudstrg'
  mount Gdrivestrg::Engine, :at => 'gdrive'

  get "home/index"
  get "home/close"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins

  root :to => 'home#index'

end

app/models/scene.rb
require 'cloudstrg/cloudstrg'


class Scene < ActiveRecord::Base
  belongs_to :user
  has_many :workspaces, dependent: :destroy

  validates :name, presence: true
  
  belongs_to :remote, :class_name => Cloudstrg::Remoteobject, :dependent => :destroy


  attr_accessor :redirection_url
  attr_accessor :session
  attr_accessor :file_content
  attr_accessor :definition

  before_save :create_remoteobject
  before_destroy :remove_remoteobject
  #before_update_attributes :update_remoteobject

  private 
    def create_remoteobject
      if self.remote
        _plugin = self.remote.cloudstrgplugin
      else
         raise CloudStrg::RONotConfigured, 'You must select the remote object driver before saving a file.' if not self.user.cloudstrgconfig
         _plugin = self.user.cloudstrgconfig.cloudstrgplugin
      end
      
      params = {:user => self.user, :plugin_id => _plugin, :redirect => redirection_url, :session => session}
      driver = CloudStrg.new_driver params
      session, url = driver.config params
      raise CloudStrg::ROValidationRequired, url if url

      params[:filename] = self.name
      params[:file_content] = definition
      definition = ""
      if self.remote
        params[:fileid] = self.remote.file_remote_id
        ro_id = driver.update_file params
      else
        ro_id = driver.create_file params
        self.remote = Cloudstrg::Remoteobject.find(ro_id)
      end

      if not self.remote
        return false
      end
    end

    def remove_remoteobject
      """
      if self.remote
        _plugin = self.remote.cloudstrgplugin
      else
         raise CloudStrg::RONotConfigured, 'You must select the remote object driver before saving a file.' if not self.user.cloudstrgconfig
         _plugin = self.user.cloudstrgconfig.cloudstrgplugin
      end
      
      params = {:user => self.user, :plugin_id => _plugin, :redirect => redirection_url, :session => session}
      driver = CloudStrg.new_driver params
      session, url = driver.config params
      raise CloudStrg::ROValidationRequired, url if url

      if self.remote
        params[:fileid] = self.remote.file_remote_id
        driver.remove_file params
      end
      """
    end

end

app/controllers/scenes_controller.rb
require 'cloudstrg/cloudstrg'

INCLUDED_METHODS = [:show, :edit, :update, :delete, :destroy, :back_edit_ajax, :show_edit_ajax]

class ScenesController < ApplicationController
  before_filter :authenticate_user!, :confWidget, :capture_cloudstrg_validation
  before_filter :set_cloudstrg_params, :only => INCLUDED_METHODS
  before_filter :check_notifications

  def confWidget
    #TODO: Choose the widget that fits better in user's device screen
    @module = 'Desktop'
    @width = 600
    @height = 500
  end

  # GET /scenes
  # GET /scenes.json
  def index
    @user = current_user
    @scenes = []
    #if @user.cloudstrgconfig
      #@scenes = @user.scenes.joins(:remote).where(:cloudstrg_remoteobjects => {:cloudstrgplugin_id => @user.cloudstrgconfig.cloudstrgplugin})
    #end
    @scenes = @user.scenes
    @scene = @scenes[0] # Default scene
    @mode = "view"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scenes }
    end
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show 
    _params = {:fileid => @scene.remote.file_remote_id}

    _, _, content = @driver.get_file _params
    @scene.definition = content
    @mode = "view"

    # Error in case of an AJAX delete error response
    @err_type = "Error delete"
    @err_msg = "You are not allowed to destroy this scene. Only the owner can delete it."

    respond_to do |format|
      format.html { render :show }# show.html.erb
      format.js
      format.json { render json: { :id => @scene.id, 
                                   :name => @scene.name, 
                                   :user_id => @scene.user_id, 
                                   :definition => @scene.definition
                                 } 
                  }
    end
  end

  # GET /scenes/new
  # GET /scenes/new.json
  def new
    @scene = Scene.new
    @mode = "edit"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scene }
    end
  end

  # GET /scenes/1/edit
  def edit
    respond_to do |format|
      
      if @user == @scene.user
        _params = {:fileid => @scene.remote.file_remote_id}

        _, _, content = @driver.get_file _params  
        @scene.definition = content
        @mode = "edit"

        format.html { render :edit }
      else
        flash[:notice] = "You are not allowed to edit this scene"
        format.html { redirect_to scenes_path }
      end
    end
   
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @user = current_user
    @scene = @user.scenes.build(params[:scene])
    @scene.redirection_url = "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/scenes"
    @scene.session = session
    @mode = "edit"

    respond_to do |format|
      begin
        if @scene.save
          session.merge!(@scene.session)
          format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
          format.json { render json: @scene, status: :created, location: @scene }
        else
          format.html { render action: "new", notice: 'Creation failed' }
          format.json { render json: @scene.errors, status: :unprocessable_entity }
        end
      rescue CloudStrg::RONotConfigured => e
        s = Netlabsession.find_by_user_id_and_session_id(@user, session[:session_id])
        if not s
          s = Netlabsession.new :user_id => @user, :session_id => session[:session_id]
        end
        s.h_params = params
        s.save
        format.html { redirect_to cloudstrg.configs_path(:redirection_url => "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/scenes", :notice => 'Please, create a plugin configuration before continue.')  }
        #format.json { redirect_to cloudstrg.configs_path }
        #format.js { redirect_to cloudstrg.configs_path }
      rescue CloudStrg::ROValidationRequired => e
        session.merge!(@scene.session)
        s = Netlabsession.find_by_user_id_and_session_id(@user, session[:session_id])
        if not s
          s = Netlabsession.new :user_id => @user, :session_id => session[:session_id]
        end
        s.h_params = params
        s.save
        format.html {redirect_to e.message}
        #format.json { redirect_to e.message }
        #format.js {render :js => "window.location.href='#{e.message}'"}
      rescue Exception => e
        puts e.message
        puts e.backtrace
        format.html { render action: "new", notice: 'Creation failed' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scenes/1
  # PUT /scenes/1.json
  def update
    @mode = "edit"
    
    respond_to do |format|
      if @scene.update_attributes(params[:scene])
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # Used to manage AJAX delete requests with JQuery dialog
  def delete
    @err_type = "Error delete"

    if @scene.user == @user
      @err_msg = "Unexpected error happened."
      respond_to do |format|
        format.html { redirect_to scenes_path }
        format.js # delete.js.erb
      end
    else
      @err_msg = "You are not allowed to destroy this scene. Only the owner can delete it."
      respond_to do |format|
        format.html { redirect_to scenes_path }
        format.js { render partial: "error_msg" }
      end
    end
  end

  def back_new_ajax
    @warn_msg = "This scene has not been saved. Do you really want to leave?"
    @go_path = scenes_path

    respond_to do |format|
      format.js
    end
  end

  def back_edit_ajax
    @warn_msg = "This scene has been modified. Changes done will be lost If you leave without saving. Do you really want to continue?"
    @go_path = scenes_path

    respond_to do |format|
      format.js { render :partial => "check_scene_changes" }
    end
  end

  def show_edit_ajax
    @warn_msg = "This scene has been modified. Changes done will be lost If you leave without saving. Do you really want to continue?"
    @go_path = scene_url(@scene)

    respond_to do |format|
      format.js { render :partial => "check_scene_changes" }
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    if @scene.user == @user
      @scene.destroy
      session.merge!(@scene.session)
      respond_to do |format|
        format.html { redirect_to scenes_url }
        format.js { render :nothing => true }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to scenes_url, notice: 'Not allowed.' }
        format.js { render :nothing => true, status: :unprocessable_entity }
        format.json { head :no_content }
      end
    end
  end

  private
  def capture_cloudstrg_validation
    @user = current_user
    s = Netlabsession.find_by_user_id_and_session_id(@user, session[:session_id])
    puts "Refererrrr:   #{request.referer}"
    continue_stored = false
    if request.referer == "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/cloudstrg/configs"
      continue_stored = true
    end
    if session.has_key? :plugin_name
      plugin = Cloudstrg::Cloudstrgplugin.find_by_plugin_name(session[:plugin_name])
      session.delete(:plugin_name)

      _params = params
      _params.merge!({:plugin_id => plugin, :user => @user, :redirect => "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/scenes", :session => session})
      driver = CloudStrg.new_driver _params
      if driver.check_referer request.referer
        continue_stored = true
        _session, url = driver.config _params
        session.merge!(_session)
        if url
          if not s
            s = Netlabsession.new :user_id => @user, :session_id => session[:session_id]
          end
          s.h_params = params
          s.save
          respond_to do |format|
            format.html {redirect_to url}
            format.json { render :json => { :redirect => url } }
            format.js {render :js => "window.location.href='#{url}'"}
          end
          return
        end
      end
    end
    if s
      if continue_stored
        if not params.has_key? :error
          params.deep_merge!(JSON.parse(s.params))
        end
        s.destroy
        if INCLUDED_METHODS.include? params[:action].to_sym
          set_cloudstrg_params
        end
        send(params[:action])
      else
        s.destroy
      end
    end
  end

  def set_cloudstrg_params
    @scene = Scene.find(params[:id])
    @user = current_user
    if not @scene.remote
      if not @user.cloudstrgconfig
        respond_to do |format|
          format.html { redirect_to cloudstrg.configs_path }
          format.json { redirect_to cloudstrg.configs_path }
          format.js { redirect_to cloudstrg.configs_path }
        end
      else
        plugin = @user.cloudstrgconfig.cloudstrgplugin
      end 
    else
      plugin = @scene.remote.cloudstrgplugin
    end
    
    if params[:redirect_url]
      _params = {:user => @user, :plugin_id => plugin, :redirect => params[:redirect_url], :session => session}
    else
      _params = {:user => @user, :plugin_id => plugin, :redirect => "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/scenes", :session => session}
    end

    if not @driver
      @driver = CloudStrg.new_driver _params
      _session, url = @driver.config _params
      session.merge!(_session)

      @scene.redirection_url = "#{request.protocol}#{Netlab::Application.config.app_host_and_port}/scenes"
      @scene.session = session
      if url
        s = Netlabsession.find_by_user_id_and_session_id(@user, session[:session_id])
        if not s
          s = Netlabsession.new :user_id => @user, :session_id => session[:session_id]
        end
        s.h_params = params

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_create.js.erb
<%= javascript_tag do %>

  function initStage() {
    var json = $("#scene_definition").val();

    if (!json)
      return;

    var editor = <%= @widget %>.getEditor();
    Netlab.loadJSON(editor, json);
  };

  function clearScene() {
    var editor = <%= @widget %>.getEditor();
    var nodes = editor.getNodes();

    for(var i = 0; i < nodes.length; i++)
      editor.removeNode(nodes[i].name);
  };

  function fillForm() {
    var name = prompt('Scene name', '');

    if (name == null)
      return false;

    $("#scene_name").val(name);

    var editor = <%= @widget %>.getEditor();

    $("#scene_definition").val(Netlab.saveJSON(editor));

    return true;
  };

<% end %>

app/views/scenes/_delete_dialog.js.erb
(function () {
  var $dialog = $('<div></div>')
    .html('<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span> This stage will be permanently deleted and cannot be recovered. Are you sure?</p>')
    .dialog({
      autoOpen: false,
      resizable: false,
      modal: true,
      title: 'Delete <%= @scene.name %>?',
      buttons: {
        "Delete": function() {
          $.ajax({
            url: '<%= scene_path(@scene) %>',
            type: 'post',
            dataType: 'script',
            data: {
              '_method': 'delete',
              'authenticity_token': '<%= form_authenticity_token %>'
            },
            success: function() {
              window.location.href = "<%= scenes_path %>";
            },
            error: function(msg) {
              <%= render "error_msg", formats: :js %>
            }
          });
          $( this ).dialog( "close" );
        },
        Cancel: function() {
          $( this ).dialog( "close" );
        }
      }
    });

  $dialog.dialog('open');
}());

app/views/scenes/_error_msg.js.erb
(function () {
  var $dialog = $('<div></div>')
    .html('<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span><%= @err_msg %></p>')
    .dialog({
      autoOpen: false,
      resizable: false,
      modal: true,
      title: '<%= @err_type %>',
      buttons: {
        Ok: function() {
          $( this ).dialog( "close" );
        }
      }
    });

  $dialog.dialog('open');
}());

app/views/scenes/_form.html.erb
<%= form_for @scene, :html => { :onSubmit => 'return fillForm();' } do |f| %>
    <% if @scene.errors.any? %>
      <div id="error_explanation" class="alert alert-error span7 offset4">
        <h4><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h4>
        <ul>
          <% @scene.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="container-fluid">

    <ul id="breadcrumb" class="breadcrumb wizard">
      <li><a href="/"><i class="icon-home"></i></a></li>
      <li><a href="/scenes">Scenes</a></li>
      <% if @scene.user %>
        <li class="active">Editing <%= @scene.name %></li>
      <% else %>
        <li class="active">New</li>
      <% end %>
    </ul>

    <div class="row-fluid container-widget">

      <div id="scene_view" class="span4 offset3">
        <div class="navbar">
          <div id="container_title" class="navbar-inner">
            <a id="scene_title" href="#" class="brand">Loading...</a>
            <% if @scene.id %>
              <span class="icon pull-right">
                <%= link_to '<i class="icon-eye-open"></i>'.html_safe, @scene, :title => 'Show', :rel => 'tooltip' %>
              </span>
            <% end %>
          </div>
        </div>
        <%= render 'netwidget' %>

        <div class="field">
          <%= f.hidden_field :name %>
        </div>
        <div class="field">
          <%= f.hidden_field :definition %>
        </div>

        <div id="form-actions" class="form-actions">
          <%= f.submit "Save", :class => 'btn btn-primary' %>
          <%= button_to_function "Clear", "clearScene()", :class => 'btn' %>
        </div>
      </div>

    </div>

  </div>
<% end %>

app/views/scenes/_initwidget.js.erb
<%= javascript_tag do %>

  function clearScene() {
    var widget = <%= @module %>.getWidget();
    var nodes = widget.getNodes();

    for(var i = 0; i < nodes.length; i++)
      widget.removeNode(nodes[i].name);
  };

  function loadStage(json) {
    if (!json)
      return;

    var widget = <%= @module %>.getWidget();
    Netlab.loadJSON(widget, json);
  };

  function initJSON() {
    $('#table_scenes input').each(function() {
      if ($(this).is(':checked')) {
        sceneId = $(this).attr('class');
        sceneValue = $(this).val();
        loadJSON(sceneId, sceneValue);
      }
    });

    <% if @scene.name %>
      <% if @mode == 'edit' %>
        <% if @scene.id %>
          sceneId = 'Editing ' + '<%= @scene.name %>';
        <% else %>
          sceneId = 'New Scene';
        <% end %>
      <% else %>
        sceneId = '<%= @scene.name %>';
      <% end %>
        sceneValue = '<%= @scene.id %>';
        loadJSON(sceneId, sceneValue);
    <% else %>
      $('#container').show();
      $('#spinner').hide();
      $('#scene_title').html('New Scene');
      loadStage("");
    <% end %>
  };

  function loadJSON(sceneId, sceneValue){
    $('#error_msg').hide();
    $('#container').hide();
    $('#spinner').show();
    $.ajax({
      url: '/scenes/' + sceneValue + '?redirect_url=' + window.location.protocol + '//' + window.location.host + '/workspaces',
      dataType: 'json',
      success: function(data) {
        if(data.redirect){
          window.location.href = data.redirect;
        }else{
          checkedValue = 0;
          $('#table_scenes input').each(function() {
            if ($(this).is(':checked')) {
              checkedValue = $(this).val();
            }
          });
          if($('#table_scenes').length){
            if (checkedValue == sceneValue) {
              $('#container').show();
              $('#spinner').hide();
              $('#scene_title').html(sceneId);
              loadStage(data.definition);
            }
          }else{
            $('#container').show();
            $('#spinner').hide();
            $('#scene_title').html(sceneId);
            loadStage(data.definition);
          }
        }
      },
      error: function (xhr, ajaxOptions, thrownError) {
        if(xhr.status != 0){
          $('#error_msg').show();
          $('#spinner').hide();
          $('#error_msg').css('width', <%= @width %>);
          $('#error_msg').css('height', <%= @height %>);
          $('#error_msg').css('border', '1px solid #D4D4D4');
          $('#spinner').hide();
          $('#error_msg').html('<div class="alert alert-danger alert-block">'+'<h4 class="alert-heading">'+xhr.status+' '+thrownError+'</h4>'+'</div>');
          $('#scene_title').html('Server Error');
        }
      }
    })
  };

  function initSpinner() {
    $('#spinner').css('width', <%= @width %>);
    $('#spinner').css('height', <%= @height %>);
    $('#spinner').css('border', '1px solid #D4D4D4');
    var opts = {
      lines: 15,
      length: 20,
      width: 6,
      radius: 20,
      color: '#77D',
      speed: 2,
      top: 200,
      left: 250
    };
    new Spinner(opts).spin(document.getElementById('spinner'));
  };

  function initWidget() {
    $('#table_scenes input').bind('click', function() {
      $('#scene_title').html('Loading...');
      clearScene();
      loadJSON($(this).attr('class'), $(this).val());
    });

    <%= @module %>.initWidget({
      container: "container",
      width: <%= @width %>,
      height: <%= @height %>,
      mode: "<%= @mode %>",
      callback: initJSON,
    });
  };

  $(window).load( function() {
    initSpinner();
    initWidget();
  });

<% end %>

app/views/scenes/_netwidget.html.erb
<div id="widget">

  <div id="spinner"></div>

  <div id="error_msg"></div>

  <div id="container" hidden="true">
    <%= render partial: 'initwidget', formats: :js %>
  </div>

</div>

app/views/scenes/_warn_msg.js.erb
(function () {
  var $dialog = $('<div></div>')
    .html('<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span><%= @warn_msg %></p>')
    .dialog({
      autoOpen: false,
      resizable: false,
      modal: true,
      title: 'Warning',
      buttons: {
        "Continue": function() {
          <%= continue_func %>();
        },
        Cancel: function() {
          $( this ).dialog( "close" );
        }
      }
    });

  $dialog.dialog('open');
}());

app/views/scenes/_widget_handler.js.erb
<%= javascript_tag do %>

  function fillForm() {
    var name = "<%=@scene.name %>";
    name = prompt('Scene name:', name);

    if (name == null)
      return false;

    $("#scene_name").val(name);

    var widget = <%= @module %>.getWidget();

    $("#scene_definition").val(Netlab.getJSON(widget));

    return true;
  };

<% end %>

app/views/scenes/back_new_ajax.js.erb
(function () {
  function continue_f() {
    window.location.href = "<%= @go_path %>";
  };

  var widget = <%= @module %>.getWidget();
  var scene = Netlab.getJSON(widget);
  var sceneObj = JSON.parse(scene);

  if (sceneObj.nodes.length > 0)
    <%= render :partial =>"warn_msg", formats: :js, :locals => { :continue_func => "continue_f" }  %>
  else
    continue_f();
}());

app/views/scenes/delete.js.erb
<%= render "delete_dialog", formats: :js %>

app/views/scenes/edit.html.erb
<%= render partial: 'widget_handler', formats: :js %>

<%= render 'form' %>

app/views/scenes/index.html.erb
<div class="container-fluid">

  <ul id="breadcrumb" class="breadcrumb wizard">
    <li><a href="/"><i class="icon-home"></i></a></li>
    <li class="active">Scenes</li>
  </ul>

  <div class="row-fluid container-widget">

    <div id="netlab_params" class="span5">

      <%= link_to '<i class="icon-plus icon-white"></i> New Scene'.html_safe, new_scene_path, :class => 'btn btn-primary pull-right new' %>

      <div class="tabbable tabbable-bordered">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab"><h4>Listing scenes</h4></a></li>
        </ul>
        <div class="tab-pane active" id="tab1">
          <table id="table_scenes" class="table table-hover table-list">
            <thead>
              <tr>
                <th></th>
                <th>Owner</th>
                <th>Name</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% if @scene.nil? %>
                <div class="alert alert-info">
                  You don't have any scenes yet.
                </div>
              <% end %>
              <% @scenes.each_with_index  do |scene, i| %>
                <tr>
                  <td>
                    <% if i == 0 %>
                      <%= radio_button_tag :id, scene.id, true, :class => scene.name %>
                    <% else %>
                      <%= radio_button_tag :id, scene.id, false, :class => scene.name %>
                    <% end %>
                  </td>
                  <td><%= scene.user.first_name %></td>
                  <td><%= scene.name %></td>
                  <td>
                    <% if scene.workspaces.empty? %>
                      <%= link_to '<i class="icon-eye-open icon-white"></i>'.html_safe, scene_path(scene), :class => 'btn btn-success btn-mini',
			  :title => 'Show', :rel => 'tooltip' %>
                      <%= link_to '<i class="icon-edit icon-white"></i>'.html_safe, edit_scene_path(scene), :class => 'btn btn-mini btn-info',
			  :title => 'Edit', :rel => 'tooltip' %>
                      <%= link_to '<i class="icon-trash icon-white"></i>'.html_safe, delete_scene_path(scene), :class => 'btn btn-mini btn-danger',
			  :title => 'Remove', :rel => 'tooltip', :remote => true %>
                    <% else %>
                      <div class="btn-group">
                        <a class="btn dropdown-toggle btn-mini btn-warning" data-toggle="dropdown" href="#">
                        <i class="icon-eye-open icon-white"></i>
                        Workspaces
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <% scene.workspaces.each  do |workspace| %>
                            <li><%= link_to "#{workspace.name}", workspace_path(workspace) %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>

    <% if not @scene.nil? %>
      <div id="scene_view" class="span6 offset1" >
        <div class="navbar">
          <div id="container_title" class="navbar-inner">
            <a id="scene_title" href="#" class="brand">Loading...</a>
          </div>
        </div>

        <%= render 'netwidget' %>
      </div>
   <% end %>

  </div>

</div>

app/views/scenes/new.html.erb
<%= render partial: 'widget_handler', formats: :js %>

<%= render 'form' %>

app/views/scenes/show.js.erb
(function () {
  var init = false;

  try {
    <%= @module %>.getWidget();
  } catch(err) {
    init = true;
    $('#dialog').html("<%=j render 'netwidget' %>");
    initWidget();
  }

  $('#dialog')
    .dialog({
      autoOpen: false,
      resizable: false,
      show: { effect: 'drop', direction: "up" },
      hide: { effect: 'drop', direction: "up" },
      width: <%= @width %> + 30,
      height: <%= @height %> + 120,
      title: '<%= @scene.name %>',
      modal: true,
      open: function(event, ui) {
        var json =
        <% if @scene.definition %>
          "<%=j @scene.definition.html_safe %>";
        <% else %>
          "";
        <% end %>

        if (!init)
          loadStage(json);
      },
      close: function(event, ui) {
        clearScene();
      },
      buttons: {
        "Edit": function() {
          window.location.href = "<%= edit_scene_path(@scene) %>";
        },
        "Destroy": function() {
          <%= render "delete_dialog", formats: :js %>
        }
      }
    });

  $('#dialog').dialog('open');
}());